version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/etc/nginx/html/:ro
  frontend:
    build:
      context: ./frontend
      args:
        NODE_ENV: development
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    env_file:
      - '.env'
    ports:
      - "8080:8080"
    command: npm run serve

  backend:
    build: ./backend
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    env_file:
      - '.env'
    volumes:
      - ./backend/app:/app
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  postgres:
    image: postgres
    environment:
      PGDATA: /data/postgres
    env_file:
      - '.env_postgres'
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    env_file:
      - '.env_postgres'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  postgres:
  pgadmin:


