version: "3"
services:
#  nginx:
#    image: nginx:stable-alpine
#    ports:
#      - "3000:80"
#    volumes:
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  frontend:
    build:
      context: ./frontend
      args:
        NODE_ENV: development
    volumes:
      - ./frontend:/app
#      - ./frontend/node_moduls
    environment:
      - NODE_ENV=developmnet
      - MONGO_USER=mike
      - MONGO_PASSWORD=password
      - SESSION_SECRET=secret
    ports:
      - "8080:8080"
    command: npm run serve

  backend:
    build: ./backend/
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    env_file:
      - '.env'
    volumes:
      - ./backend/app:/app:ro
#    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password123!
      POSTGRES_DB: fastapi
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: AdminPassword123!
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  postgres:
  pgadmin:


