"""added users table

Revision ID: 396901371947
Revises: ca007de6483f
Create Date: 2021-12-25 20:27:39.614635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396901371947'
down_revision = 'ca007de6483f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('todos', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('todos', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'todos', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'owner_id')
    op.drop_column('todos', 'created_at')
    op.drop_table('users')
    # ### end Alembic commands ###
